environment_name         = "dev"
availability_zones      = ["eu-west-2a", "eu-west-2b", "eu-west-2c"]
desired_count            = 0
db_instance_class        = "db.t4g.micro"
domain_name              = "dev.rollfinders.com"
hosted_zone_name         = "rollfinders.com"
enable_custom_domain     = false
enable_nat_gateway       = false
enable_analytics_service = false
enable_ec2_app_host      = true
ec2_app_instance_type    = "t3.medium"
ec2_app_root_volume_size = 30
