package domain

const (
	ActorUserIDHeader = "X-Actor-User-ID"
	ContentTypeHeader = "Content-Type"
	ContentTypeJSON   = "application/json"
	IdempotencyHeader = "Idempotency-Key"
	RequestIDHeader   = "X-Request-ID"

	AuthBearerPrefix = "Bearer "

	ContextKeyRequestID     = "request_id"
	RequestIDUnknown        = "request_unknown"
	RequestIDPrefix         = "req_"
	RollFindersGatewayValue = "api"

	ProxyKeyAcademy       = "academy"
	ProxyKeyAuthorisation = "authorisation"
	ProxyKeyBooking       = "booking"
	ProxyKeyCourse        = "course"
	ProxyKeyLegacy        = "legacy"
	ProxyKeyOrganisation  = "organisation"
	ProxyKeyPayment       = "payment"
	ProxyKeyPricing       = "pricing"
	ProxyKeySubscriptions = "subscriptions"
	ProxyKeyTransfer      = "transfer"
	ProxyKeyUsageLimits   = "usage_limits"
	ProxyKeyUser          = "user"
	ProxyKeyWallet        = "wallet"

	ForwardedHostHeader         = "X-Forwarded-Host"
	ForwardedProtoHeader        = "X-Forwarded-Proto"
	RollFindersGatewayHeader    = "X-RollFinders-Gateway"
	OrganisationIDHeader        = "X-Organisation-ID"
	OrganizationIDHeader        = "X-Organization-ID"
	SubscriptionOwnerIDHeader   = "X-Subscription-Owner-ID"
	SubscriptionOwnerTypeHeader = "X-Subscription-Owner-Type"

	RootPath                         = "/"
	V1Path                           = "/v1"
	AuthorisationProxyPath           = "/v1/authorisation"
	AuthorisationProxyPrefix         = "/v1/authorisation/"
	AuthProxyPrefix                  = "/auth/"
	V1AuthProxyPrefix                = "/v1/auth/"
	V1AccountsProxyPrefix            = "/v1/accounts/"
	LegacyProxyPath                  = "/legacy"
	LegacyProxyPrefix                = "/legacy/"
	OpenAPIPath                      = "/openapi.json"
	HealthPath                       = "/healthz"
	ReadyPath                        = "/readyz"
	AuthorisationAuthorizePath       = "/v1/authorize"
	SubscriptionEntitlementCheckPath = "/v1/entitlements/check"
	UsageLimitsReservationsPath      = "/v1/usage-limits/reservations"
	UsageLimitsReservationPathFormat = "/v1/usage-limits/reservations/%s/%s"

	TransferType             = "TRANSFER"
	TransferReferenceType    = "transfer"
	TransferCreatePath       = "/v1/transfers"
	TransferStatusPathFormat = "/v1/transfers/%s/status"
	WalletTransferPath       = "/v1/wallets/transfer"

	TransferStatusProcessing = "PROCESSING"
	TransferStatusCompleted  = "COMPLETED"
	TransferStatusFailed     = "FAILED"

	ErrorCodeInvalidRequestBody         = "invalid_request_body"
	ErrorCodeTransferServiceUnavailable = "transfer_service_unavailable"
	ErrorCodeTransferResponseInvalid    = "transfer_response_invalid"
	ErrorCodeWalletServiceUnavailable   = "wallet_service_unavailable"
	ErrorCodeWalletResponseInvalid      = "wallet_response_invalid"

	ErrorMessageInvalidRequestBody     = "Request body could not be read."
	ErrorMessageTransferCreateFailed   = "Transfer service could not create the transfer request."
	ErrorMessageTransferCompleteFailed = "Transfer service could not complete the transfer request."
	ErrorMessageTransferInvalid        = "Transfer service returned an invalid transfer response."
	ErrorMessageWalletApplyFailed      = "Wallet service could not apply the transfer ledger movement."
	ErrorMessageWalletInvalid          = "Wallet service returned an invalid transfer response."
	ErrorMessageWalletUnsuccessful     = "Wallet service returned an unsuccessful response."

	JSONKeyError               = "error"
	JSONKeyCode                = "code"
	JSONKeyMessage             = "message"
	JSONKeyRequestID           = "request_id"
	JSONKeyDetails             = "details"
	JSONKeyTransfer            = "transfer"
	JSONKeyWalletTransaction   = "wallet_transaction"
	JSONKeyType                = "type"
	JSONKeySourceWalletID      = "source_wallet_id"
	JSONKeyDestinationWalletID = "destination_wallet_id"
	JSONKeyAmount              = "amount"
	JSONKeyCurrency            = "currency"
	JSONKeyReferenceType       = "reference_type"
	JSONKeyReferenceID         = "reference_id"
	JSONKeyDescription         = "description"
	JSONKeyStatus              = "status"
	JSONKeyFailureReason       = "failure_reason"

	DecisionAllow = "allow"

	OwnerTypeAcademy      = "academy"
	OwnerTypeOrganisation = "organisation"
	OwnerTypeApplication  = "application"
	OwnerTypePractitioner = "practitioner"

	QueryOwnerID        = "owner_id"
	QueryOwnerIDCamel   = "ownerId"
	QueryOwnerType      = "owner_type"
	QueryOwnerTypeCamel = "ownerType"
	QueryOrganisationID = "organisationId"
)
