import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import path from "node:path";

const root = process.cwd();

function readSource(filePath: string) {
  return readFileSync(path.join(root, filePath), "utf8");
}

test("events expose integration URI and QR code routes", () => {
  const helperSource = readSource("apps/portal/src/lib/event-share-links.ts");
  const permanentRouteSource = readSource("apps/portal/src/app/e/[id]/page.tsx");
  const qrRouteSource = readSource("apps/portal/src/app/api/events/[id]/qrcode/route.ts");
  const dashboardSource = readSource("apps/portal/src/app/dashboard/AdminDashboardWorkspace.tsx");
  const courseDetailSource = readSource("apps/portal/src/app/courses/[id]/page.tsx");
  const openMatDetailSource = readSource("apps/portal/src/app/open-mats/[id]/page.tsx");
  const publicDetailSource = readSource("apps/portal/src/app/_components/PublicEventDetailPage/PublicEventDetailPage.tsx");
  const inlineDirectionsSource = readSource("apps/portal/src/app/_components/InlineDirectionsButton/InlineDirectionsButton.tsx");
  const mapWithDirectionSource = readSource("apps/portal/src/app/_components/MapWithDirection/MapWithDirection.tsx");
  const publicListingWarningSource = readSource("apps/portal/src/app/_components/PublicListingWarning/PublicListingWarning.tsx");
  const spotCounterSource = readSource("apps/portal/src/app/_components/SpotCounter/SpotCounter.tsx");
  const publicFlyerSource = readSource("apps/portal/src/app/_components/PublicEventFlyer/PublicEventFlyer.tsx");
  const eventSummaryTagSource = readSource("apps/portal/src/app/_components/EventSummaryTag/EventSummaryTag.tsx");
  const summaryTileSource = readSource("apps/portal/src/app/_components/SummaryTile/index.ts");
  const bookEventButtonSource = readSource("apps/portal/src/app/_components/BookEventButton/BookEventButton.tsx");
  const panelContextSource = readSource("apps/portal/src/app/_components/PanelContext/index.ts");
  const warningPanelSource = readSource("apps/portal/src/app/_components/WarningPanel/index.ts");
  const coursesSource = readSource("apps/portal/src/lib/courses.ts");

  assert.match(helperSource, /eventPermanentPath/);
  assert.match(helperSource, /`\/e\/\$\{eventId\}`/);
  assert.match(helperSource, /eventPermanentUrl/);
  assert.match(helperSource, /NEXTAUTH_URL/);
  assert.match(permanentRouteSource, /eventPublicPath/);
  assert.match(permanentRouteSource, /redirect\(eventPublicPath\(event\)\)/);
  assert.match(qrRouteSource, /QRCode\.toString/);
  assert.match(qrRouteSource, /eventPermanentUrl\(id\)/);
  assert.match(qrRouteSource, /image\/svg\+xml/);
  assert.match(dashboardSource, /Integration URI/);
  assert.match(dashboardSource, /QR Code/);
  assert.match(dashboardSource, /eventQrCodePath\(event\.id\)/);
  assert.match(dashboardSource, /InlineDirectionsButton/);
  assert.match(courseDetailSource, /eventPermanentPath\(event\.id\)/);
  assert.match(courseDetailSource, /eventQrCodePath\(event\.id\)/);
  assert.match(courseDetailSource, /PublicEventDetailPage/);
  assert.doesNotMatch(courseDetailSource, />Open URI</);
  assert.match(openMatDetailSource, /eventPermanentPath\(event\.id\)/);
  assert.match(openMatDetailSource, /eventQrCodePath\(event\.id\)/);
  assert.match(openMatDetailSource, /PublicEventDetailPage/);
  assert.doesNotMatch(openMatDetailSource, />Open URI</);
  assert.match(publicDetailSource, /aria-label="Event QR code"/);
  assert.doesNotMatch(publicDetailSource, />Event QR Code</);
  assert.doesNotMatch(publicDetailSource, /permanentUrl/);
  assert.match(publicDetailSource, /qrCodeHref/);
  assert.match(publicDetailSource, /MapWithDirection/);
  assert.match(publicDetailSource, /SummaryTile/);
  assert.ok(publicDetailSource.indexOf("<PublicEventFlyer") < publicDetailSource.indexOf("<PublicListingWarning"));
  assert.ok(publicDetailSource.indexOf("<PublicListingWarning") < publicDetailSource.indexOf("<dl className=\"grid gap-3"));
  assert.ok(publicDetailSource.indexOf("<dl className=\"grid gap-3") < publicDetailSource.indexOf("<BookingAction"));
  assert.match(publicDetailSource, /BookEventButton/);
  assert.match(bookEventButtonSource, /Omit<ButtonProps, "children">/);
  assert.match(bookEventButtonSource, /loading/);
  assert.match(bookEventButtonSource, /return "Book"/);
  assert.match(bookEventButtonSource, /text-lg font-black/);
  assert.match(eventSummaryTagSource, /SummaryTile as EventSummaryTag/);
  assert.match(summaryTileSource, /export type SummaryTileProps/);
  assert.match(summaryTileSource, /PanelContext/);
  assert.match(summaryTileSource, /className/);
  assert.match(summaryTileSource, /pin/);
  assert.match(summaryTileSource, /text-base font-normal uppercase leading-5/);
  assert.match(summaryTileSource, /text-base font-normal leading-5/);
  assert.doesNotMatch(summaryTileSource, /font-black|font-semibold|text-xs/);
  assert.match(panelContextSource, /export type PanelContextProps/);
  assert.match(panelContextSource, /pin\?: ReactNode/);
  assert.match(panelContextSource, /p-3/);
  assert.match(publicListingWarningSource, /WarningPanel/);
  assert.match(warningPanelSource, /export type WarningPanelProps/);
  assert.match(warningPanelSource, /title: ReactNode/);
  assert.match(warningPanelSource, /children: ReactNode/);
  assert.match(warningPanelSource, /tone\?: WarningPanelTone/);
  assert.match(mapWithDirectionSource, /InlineDirectionsButton/);
  assert.match(mapWithDirectionSource, /google\.com\/maps/);
  assert.match(mapWithDirectionSource, /output=embed/);
  assert.match(mapWithDirectionSource, /<iframe/);
  assert.match(publicFlyerSource, /defaultFlyerImage\.png/);
  assert.doesNotMatch(publicFlyerSource, /SpotCounter/);
  assert.match(spotCounterSource, /bookedCount/);
  assert.match(spotCounterSource, /availableSpots/);
  assert.match(spotCounterSource, /20\)/);
  assert.doesNotMatch(spotCounterSource, /border-stone-300|shadow-md|bg-white/);
  assert.match(spotCounterSource, /text-xs font-black leading-5/);
  assert.match(spotCounterSource, /spots available/);
  assert.match(inlineDirectionsSource, /directionsUrl\(trimmedAddress\)/);
  assert.match(inlineDirectionsSource, /target="_blank"/);
  assert.match(inlineDirectionsSource, /rel="noreferrer"/);
  assert.match(inlineDirectionsSource, /size="sm"/);
  assert.match(coursesSource, /occurrenceDateParam \? startOfDay/);
  assert.match(coursesSource, /: startOfDay\(now\)/);
});
