package routes

import "testing"

func TestGatewayResourceCatalogIncludesTargetsForAPIPermissions(t *testing.T) {
	expectedTargets := map[GatewayPermissionName]GatewayTargetPath{
		PermissionAcademyCreate:                      AcademiesPath,
		PermissionAcademyDelete:                      AcademyPath,
		PermissionAcademyMemberAssign:                AcademiesAcademyIdMembers,
		PermissionAcademyMemberRead:                  AcademiesAcademyIdMembers,
		PermissionAcademyMemberRemove:                AcademiesAcademyIdMembersUserId,
		PermissionAcademyMembershipAssign:            Memberships,
		PermissionAcademyMembershipRead:              Memberships,
		PermissionAcademyMembershipRemove:            MembershipsMembershipId,
		PermissionAcademySearchHide:                  AcademiesAcademyIdSearchHide,
		PermissionAcademyUpdate:                      AcademyPath,
		PermissionAccountRead:                        AccountsAccountId,
		PermissionAccountUpdate:                      AccountsAccountId,
		PermissionAuthMfaUpdate:                      AuthMfaSetup,
		PermissionAuthPasswordUpdate:                 AuthChangePassword,
		PermissionAuthSessionDelete:                  AuthSessionsSessionId,
		PermissionAuthSessionRead:                    AuthSessions,
		PermissionUserCreate:                         Users,
		PermissionUserDelete:                         UsersUserId,
		PermissionUserRead:                           UsersUserId,
		PermissionUserSearch:                         Users,
		PermissionUserUpdate:                         UsersUserId,
		PermissionOrganisationApplicationRead:        ApplicationsApplicationId,
		PermissionOrganisationApplicationSearch:      Applications,
		PermissionOrganisationCreate:                 Organisations,
		PermissionOrganisationRead:                   OrganisationsOrganisationId,
		PermissionOrganisationSearch:                 Organisations,
		PermissionOrganisationUpdate:                 OrganisationsOrganisationId,
		PermissionCourseActivityCreate:               CoursesCourseIdActivities,
		PermissionCourseActivityDelete:               ActivitiesActivityId,
		PermissionCourseActivityRead:                 CoursesCourseIdActivities,
		PermissionCourseActivityUpdate:               ActivitiesActivityId,
		PermissionCourseCreate:                       CoursesPath,
		PermissionCourseDelete:                       CoursePath,
		PermissionCourseTypeCreate:                   CourseTypesPath,
		PermissionCourseTypeDelete:                   CourseTypePath,
		PermissionCourseTypeUpdate:                   CourseTypePath,
		PermissionCourseUpdate:                       CoursePath,
		PermissionBookingCancel:                      BookingsBookingIdCancel,
		PermissionBookingComplete:                    BookingsBookingIdComplete,
		PermissionBookingConfirm:                     BookingsBookingIdConfirm,
		PermissionBookingCreate:                      Bookings,
		PermissionBookingParticipantAttendanceRecord: BookingsBookingIdParticipantsParticipantIdAttendance,
		PermissionBookingParticipantCreate:           BookingsBookingIdParticipants,
		PermissionBookingParticipantRead:             BookingsBookingIdParticipants,
		PermissionBookingPaymentLink:                 BookingsBookingIdPaymentLink,
		PermissionBookingPaymentRecord:               BookingsBookingIdPaymentReceived,
		PermissionBookingRead:                        BookingsBookingId,
		PermissionPaymentAccountConnect:              PaymentAccountsStripeConnect,
		PermissionPaymentAccountDisconnect:           PaymentAccountsStripeDisconnect,
		PermissionPaymentAccountRead:                 PaymentAccountsStripe,
		PermissionPaymentCancel:                      PaymentsPaymentIdCancel,
		PermissionPaymentCapture:                     PaymentsPaymentIdCapture,
		PermissionPaymentCheckoutCreate:              Checkouts,
		PermissionPaymentClientCreate:                Clients,
		PermissionPaymentCreate:                      Payments,
		PermissionPaymentPayeeBalanceRead:            PayeesPayeeIdBalances,
		PermissionPaymentRead:                        PaymentsPaymentId,
		PermissionPaymentRefundCreate:                PaymentsPaymentIdRefunds,
		PermissionPaymentRefundRead:                  PaymentsPaymentIdRefunds,
		PermissionPaymentSearch:                      Payments,
		PermissionPayoutRequestApprove:               PayoutRequestsPayoutRequestIdApprove,
		PermissionPayoutRequestCancel:                PayoutRequestsPayoutRequestIdCancel,
		PermissionPayoutRequestCreate:                PayeesPayeeIdPayoutRequests,
		PermissionPayoutRequestHold:                  PayoutRequestsPayoutRequestIdHold,
		PermissionPayoutRequestMarkPaid:              PayoutRequestsPayoutRequestIdMarkPaid,
		PermissionPayoutRequestRead:                  PayoutRequestsPayoutRequestId,
		PermissionPayoutRequestReject:                PayoutRequestsPayoutRequestIdReject,
		PermissionPayoutRequestRelease:               PayoutRequestsPayoutRequestIdRelease,
		PermissionPayoutRequestSearch:                PayoutRequests,
		PermissionAuthorisationAuthorize:             AuthorisationAuthorize,
		PermissionAuthorisationPermissionCreate:      AuthorisationPermissions,
		PermissionAuthorisationPermissionRead:        AuthorisationPermissions,
		PermissionAuthorisationPermissionUpdate:      AuthorisationPermissionsPermissionId,
		PermissionAuthorisationResourceCreate:        AuthorisationResources,
		PermissionAuthorisationResourceRead:          AuthorisationResources,
		PermissionAuthorisationRoleCreate:            AuthorisationRoles,
		PermissionAuthorisationRolePermissionAssign:  AuthorisationRolesRoleIdPermissions,
		PermissionAuthorisationRolePermissionRead:    AuthorisationRolesRoleIdPermissions,
		PermissionAuthorisationRolePermissionRemove:  AuthorisationRolesRoleIdPermissionsPermissionId,
		PermissionAuthorisationRoleRead:              AuthorisationRolesRoleId,
		PermissionAuthorisationRoleUpdate:            AuthorisationRolesRoleId,
		PermissionAuthorisationUserPermissionAssign:  AuthorisationUsersUserIdPermissions,
		PermissionAuthorisationUserPermissionRead:    AuthorisationUsersUserIdPermissions,
		PermissionAuthorisationUserPermissionRemove:  AuthorisationUsersUserIdPermissionsAssignmentId,
		PermissionAuthorisationUserRoleAssign:        AuthorisationUsersUserIdRoles,
		PermissionAuthorisationUserRoleRead:          AuthorisationUsersUserIdRoles,
		PermissionAuthorisationUserRoleRemove:        AuthorisationUsersUserIdRolesAssignmentId,
		PermissionSubscriptionProductRead:            SubscriptionProducts,
		PermissionSubscriptionProductManage:          SubscriptionProducts,
		PermissionSubscriptionPlanRead:               SubscriptionPlans,
		PermissionSubscriptionPlanManage:             SubscriptionPlans,
		PermissionSubscriptionAvailableFeaturesRead:  SubscriptionApplicationAvailableFeatures,
		PermissionSubscriptionSubscriptionRead:       SubscriptionApplicationSubscriptions,
		PermissionSubscriptionSubscriptionManage:     SubscriptionApplicationSubscriptions,
		PermissionSubscriptionEntitlementRead:        SubscriptionApplicationEntitlements,
	}

	catalog := GatewayResourceCatalog()
	for permission, target := range expectedTargets {
		resource, ok := catalog[permission]
		if !ok {
			t.Fatalf("permission %q missing from gateway resource catalog", permission)
		}
		if resource.Target != target {
			t.Fatalf("permission %q target = %q, want %q", permission, resource.Target, target)
		}
	}
}
