CREATE OR REPLACE PROCEDURE "seedAuthorisationCatalog"()
LANGUAGE plpgsql
SET search_path TO authorisation, public
AS $$
BEGIN
    INSERT INTO permissions (id, code, name, description)
    VALUES
        ('perm_academy_create', 'academy.create', 'Create academies', 'Allows creating academy resources.'),
        ('perm_academy_view', 'academy.view', 'View academies', 'Allows viewing academy records and public/admin profile details.'),
        ('perm_academy_read', 'academy.read', 'Read academies', 'Allows reading academy management data.'),
        ('perm_academy_edit', 'academy.edit', 'Edit academies', 'Allows editing academy records and profile fields.'),
        ('perm_academy_update', 'academy.update', 'Update academies', 'Allows updating academy resources.'),
        ('perm_academy_delete', 'academy.delete', 'Delete academies', 'Allows deleting academy resources.'),
        ('perm_academy_claim', 'academy.claim.view', 'View academy claim workflow', 'Allows viewing academy ownership claim workflow access.'),
        ('perm_academy_claim_approve', 'academy.claim.approve', 'Approve academy claims', 'Allows approving academy ownership claims.'),
        ('perm_academy_verify', 'academy.verify', 'Verify academies', 'Allows verifying academy records.'),
        ('perm_academy_unverify', 'academy.unverify', 'Unverify academies', 'Allows removing academy verification.'),
        ('perm_academy_suspend', 'academy.suspend', 'Suspend academies', 'Allows suspending academy management or public visibility.'),
        ('perm_academy_activate', 'academy.activate', 'Activate academies', 'Allows reactivating suspended academy records.'),
        ('perm_academy_archive', 'academy.archive', 'Archive academies', 'Allows archiving academy records.'),
        ('perm_academy_restore', 'academy.restore', 'Restore academies', 'Allows restoring archived academy records.'),
        ('perm_academy_audit_view', 'academy.audit.view', 'View academy audit', 'Allows viewing academy audit history.'),
        ('perm_academy_public_enabled', 'academy.public.enabled', 'Enable public academy listing', 'Allows enabling academy public listing and discovery visibility.'),
        ('perm_academy_search', 'academy.search', 'Search academies', 'Allows listing and searching academy resources.'),
        ('perm_academy_member_read', 'academy.member.read', 'Read academy members', 'Allows reading academy member records.'),
        ('perm_academy_member_add', 'academy.member.add', 'Add academy members', 'Allows adding users to academy membership.'),
        ('perm_academy_member_assign', 'academy.member.assign', 'Assign academy members', 'Allows assigning users to academy membership.'),
        ('perm_academy_member_remove', 'academy.member.remove', 'Remove academy members', 'Allows removing users from academy membership.'),
        ('perm_academy_membership_read', 'academy.membership.read', 'Read academy memberships', 'Allows reading academy memberships for the current user or scope.'),
        ('perm_academy_profile_read', 'academy.profile.read', 'Read academy profile', 'Allows reading editable academy profile data.'),
        ('perm_academy_profile_update', 'academy.profile.update', 'Update academy profile', 'Allows updating academy profile data.'),
        ('perm_academy_social_read', 'academy.social.read', 'Read academy social links', 'Allows reading academy social links.'),
        ('perm_academy_social_update', 'academy.social.update', 'Update academy social links', 'Allows creating, updating, or removing academy social links.'),
        ('perm_course_create', 'course.create', 'Create courses', 'Allows creating courses and events.'),
        ('perm_course_read', 'course.read', 'Read courses', 'Allows reading course and event records.'),
        ('perm_course_search', 'course.search', 'Search courses', 'Allows listing and searching courses and events.'),
        ('perm_course_update', 'course.update', 'Update courses', 'Allows updating courses and events.'),
        ('perm_course_delete', 'course.delete', 'Delete courses', 'Allows deleting courses and events.'),
        ('perm_course_activity_create', 'course.activity.create', 'Create course activities', 'Allows creating activities for a course or event.'),
        ('perm_course_activity_read', 'course.activity.read', 'Read course activities', 'Allows reading course activity records.'),
        ('perm_course_activity_update', 'course.activity.update', 'Update course activities', 'Allows updating course activity records.'),
        ('perm_course_activity_delete', 'course.activity.delete', 'Delete course activities', 'Allows deleting course activity records.'),
        ('perm_course_type_create', 'course.type.create', 'Create course types', 'Allows creating course type definitions.'),
        ('perm_course_type_read', 'course.type.read', 'Read course types', 'Allows reading course type definitions.'),
        ('perm_course_type_update', 'course.type.update', 'Update course types', 'Allows updating course type definitions.'),
        ('perm_course_type_delete', 'course.type.delete', 'Delete course types', 'Allows deleting course type definitions.'),
        ('perm_booking_create', 'booking.create', 'Create bookings', 'Allows creating booking records.'),
        ('perm_booking_read', 'booking.read', 'Read bookings', 'Allows reading booking records.'),
        ('perm_booking_view', 'booking.view', 'View bookings', 'Allows viewing bookings.'),
        ('perm_booking_cancel', 'booking.cancel', 'Cancel bookings', 'Allows cancelling bookings.'),
        ('perm_booking_confirm', 'booking.confirm', 'Confirm bookings', 'Allows confirming bookings.'),
        ('perm_booking_complete', 'booking.complete', 'Complete bookings', 'Allows marking bookings as complete.'),
        ('perm_booking_payment_received', 'booking.payment_received', 'Record booking payment received', 'Allows marking booking payment as received.'),
        ('perm_booking_payment_link', 'booking.payment_link', 'Create booking payment links', 'Allows creating payment links for bookings.'),
        ('perm_booking_participant_create', 'booking.participant.create', 'Create booking participants', 'Allows adding participants to bookings.'),
        ('perm_booking_participant_read', 'booking.participant.read', 'Read booking participants', 'Allows reading booking participant records.'),
        ('perm_booking_participant_attendance_record', 'booking.participant.attendance.record', 'Record booking attendance', 'Allows recording participant attendance for bookings.'),
        ('perm_payment_client_create', 'payment.client.create', 'Create payment clients', 'Allows creating payment client records.'),
        ('perm_payment_checkout_create', 'payment.checkout.create', 'Create payment checkouts', 'Allows creating checkout sessions.'),
        ('perm_payment_checkout_callback', 'payment.checkout.callback', 'Handle payment checkout callbacks', 'Allows handling checkout result callbacks.'),
        ('perm_payment_course_occurrence_checkout_create', 'payment.course_occurrence_checkout.create', 'Create course occurrence checkouts', 'Allows creating course occurrence checkout sessions.'),
        ('perm_payment_course_occurrence_checkout_callback', 'payment.course_occurrence_checkout.callback', 'Handle course occurrence checkout callbacks', 'Allows handling course occurrence checkout result callbacks.'),
        ('perm_payment_create', 'payment.create', 'Create payments', 'Allows creating payment records.'),
        ('perm_payment_read', 'payment.read', 'Read payments', 'Allows reading payment records.'),
        ('perm_payment_search', 'payment.search', 'Search payments', 'Allows listing payment records in scope.'),
        ('perm_payment_capture', 'payment.capture', 'Capture payments', 'Allows capturing authorised payments.'),
        ('perm_payment_cancel', 'payment.cancel', 'Cancel payments', 'Allows cancelling payments.'),
        ('perm_payment_report_revenue_read', 'payment.report.revenue.read', 'Read payment revenue reports', 'Allows reading gross payment revenue metrics in scope.'),
        ('perm_payment_report_refund_read', 'payment.report.refund.read', 'Read payment refund reports', 'Allows reading payment refund metrics in scope.'),
        ('perm_payment_report_platform_revenue_read', 'payment.report.platform_revenue.read', 'Read platform payment revenue reports', 'Allows reading platform commission and platform revenue metrics.'),
        ('perm_payment_refund', 'payment.refund', 'Refund payments', 'Allows creating payment refunds.'),
        ('perm_payment_refund_read', 'payment.refund.read', 'Read payment refunds', 'Allows reading payment refund records.'),
        ('perm_payment_payee_balance_read', 'payment.payee.balance.read', 'Read payee balances', 'Allows reading payee balance records.'),
        ('perm_payment_webhook_receive', 'payment.webhook.receive', 'Receive payment webhooks', 'Allows receiving payment provider webhooks.'),
        ('perm_payment_outbox_dispatch', 'payment.outbox.dispatch', 'Dispatch payment outbox', 'Allows dispatching payment service outbox events.'),
        ('perm_payout_request_create', 'payout.request.create', 'Create payout requests', 'Allows creating payout requests.'),
        ('perm_payout_request_read', 'payout.request.read', 'Read payout requests', 'Allows reading payout request records.'),
        ('perm_payout_request_approve', 'payout.request.approve', 'Approve payout requests', 'Allows approving payout requests.'),
        ('perm_payout_request_reject', 'payout.request.reject', 'Reject payout requests', 'Allows rejecting payout requests.'),
        ('perm_payout_request_hold', 'payout.request.hold', 'Hold payout requests', 'Allows placing payout requests on hold.'),
        ('perm_payout_request_release', 'payout.request.release', 'Release payout requests', 'Allows releasing payout requests from hold.'),
        ('perm_payout_request_mark_paid', 'payout.request.mark_paid', 'Mark payout requests paid', 'Allows marking payout requests as paid.'),
        ('perm_payout_request_cancel', 'payout.request.cancel', 'Cancel payout requests', 'Allows cancelling payout requests.'),
        ('perm_auth_register', 'auth.register', 'Register users', 'Allows registering user identities.'),
        ('perm_auth_login', 'auth.login', 'Login users', 'Allows authenticating user identities.'),
        ('perm_auth_logout', 'auth.logout', 'Logout users', 'Allows ending authenticated sessions.'),
        ('perm_auth_refresh', 'auth.refresh', 'Refresh sessions', 'Allows refreshing authenticated sessions.'),
        ('perm_auth_password_change', 'auth.password.change', 'Change password', 'Allows changing the authenticated user password.'),
        ('perm_auth_password_reset_request', 'auth.password_reset.request', 'Request password reset', 'Allows requesting a password reset flow.'),
        ('perm_auth_password_reset_validate', 'auth.password_reset.validate', 'Validate password reset', 'Allows validating a password reset token.'),
        ('perm_auth_password_reset_confirm', 'auth.password_reset.confirm', 'Confirm password reset', 'Allows confirming a password reset.'),
        ('perm_auth_session_read', 'auth.session.read', 'Read sessions', 'Allows reading authenticated sessions.'),
        ('perm_auth_session_revoke', 'auth.session.revoke', 'Revoke sessions', 'Allows revoking authenticated sessions.'),
        ('perm_auth_mfa_setup', 'auth.mfa.setup', 'Set up MFA', 'Allows starting MFA setup.'),
        ('perm_auth_mfa_verify', 'auth.mfa.verify', 'Verify MFA', 'Allows verifying MFA challenges.'),
        ('perm_auth_credentials_authenticate', 'auth.credentials.authenticate', 'Authenticate credentials', 'Allows validating credentials through internal authentication APIs.'),
        ('perm_account_read', 'account.read', 'Read accounts', 'Allows reading user account records.'),
        ('perm_user_create', 'user.create', 'Create users', 'Allows creating users.'),
        ('perm_user_read', 'user.read', 'Read users', 'Allows reading user administration data.'),
        ('perm_user_update', 'user.update', 'Update users', 'Allows updating managed users.'),
        ('perm_user_delete', 'user.delete', 'Delete users', 'Allows deleting users.'),
        ('perm_user_mutate', 'user.mutate', 'Run user mutations', 'Allows running named user mutation actions.'),
        ('perm_organisation_create', 'organisation.create', 'Create organisations', 'Allows creating organisation records.'),
        ('perm_organisation_read', 'organisation.read', 'Read organisations', 'Allows reading organisation records.'),
        ('perm_organisation_update', 'organisation.update', 'Update organisations', 'Allows updating organisation records.'),
        ('perm_organisation_application_manage', 'organisation.application.manage', 'Manage organisation applications', 'Allows managing application enablement.'),
        ('perm_authorisation_permission_create', 'authorisation.permission.create', 'Create permissions', 'Allows creating permission definitions.'),
        ('perm_authorisation_permission_read', 'authorisation.permission.read', 'Read permissions', 'Allows reading permission definitions.'),
        ('perm_authorisation_permission_search', 'authorisation.permission.search', 'Search permissions', 'Allows listing and searching permission definitions.'),
        ('perm_authorisation_permission_update', 'authorisation.permission.update', 'Update permissions', 'Allows updating permission definitions.'),
        ('perm_authorisation_role_create', 'authorisation.role.create', 'Create roles', 'Allows creating role bundles.'),
        ('perm_authorisation_role_read', 'authorisation.role.read', 'Read roles', 'Allows reading role bundles.'),
        ('perm_authorisation_role_search', 'authorisation.role.search', 'Search roles', 'Allows listing and searching role bundles.'),
        ('perm_authorisation_role_update', 'authorisation.role.update', 'Update roles', 'Allows updating role bundles.'),
        ('perm_authorisation_role_permission_add', 'authorisation.role_permission.add', 'Add role permissions', 'Allows adding permissions to role bundles.'),
        ('perm_authorisation_role_permission_assign', 'authorisation.role_permission.assign', 'Assign role permissions', 'Allows assigning permissions to role bundles.'),
        ('perm_authorisation_role_permission_read', 'authorisation.role_permission.read', 'Read role permissions', 'Allows reading role-permission mappings.'),
        ('perm_authorisation_role_permission_remove', 'authorisation.role_permission.remove', 'Remove role permissions', 'Allows removing permissions from role bundles.'),
        ('perm_authorisation_user_role_assign', 'authorisation.user_role.assign', 'Assign user roles', 'Allows assigning roles to users.'),
        ('perm_authorisation_user_role_read', 'authorisation.user_role.read', 'Read user roles', 'Allows reading user role assignments.'),
        ('perm_authorisation_user_role_remove', 'authorisation.user_role.remove', 'Remove user roles', 'Allows removing user role assignments.'),
        ('perm_authorisation_user_permission_assign', 'authorisation.user_permission.assign', 'Assign user permissions', 'Allows assigning direct user permissions.'),
        ('perm_authorisation_user_permission_read', 'authorisation.user_permission.read', 'Read user permissions', 'Allows reading direct user permission assignments.'),
        ('perm_authorisation_user_permission_remove', 'authorisation.user_permission.remove', 'Remove user permissions', 'Allows removing direct user permission assignments.'),
        ('perm_authorisation_effective_permission_read', 'authorisation.effective_permission.read', 'Read effective permissions', 'Allows reading effective permissions for a user.'),
        ('perm_authorisation_authorize', 'authorisation.authorize', 'Evaluate authorisation', 'Allows calling the authorisation decision endpoint.'),
        ('perm_academy_publish', 'academy.publish', 'Publish academies', 'Allows publishing academy records to marketplace surfaces.'),
        ('perm_academy_unpublish', 'academy.unpublish', 'Unpublish academies', 'Allows removing academy records from marketplace surfaces.'),
        ('perm_academy_profile_location_update', 'academy.profile.location.update', 'Update academy profile location', 'Allows updating academy address and geocoding profile fields.'),
        ('perm_academy_profile_media_update', 'academy.profile.media.update', 'Update academy profile media', 'Allows updating academy profile media.'),
        ('perm_academy_profile_contact_update', 'academy.profile.contact.update', 'Update academy profile contact', 'Allows updating academy profile contact details.'),
        ('perm_academy_profile_settings_update', 'academy.profile.settings.update', 'Update academy profile settings', 'Allows updating academy profile settings.'),
        ('perm_academy_member_update', 'academy.member.update', 'Update academy members', 'Allows updating academy member role or status.'),
        ('perm_academy_member_owner_assign', 'academy.member.owner.assign', 'Assign academy owners', 'Allows assigning academy owner membership.'),
        ('perm_academy_member_owner_transfer', 'academy.member.owner.transfer', 'Transfer academy ownership', 'Allows transferring academy ownership.'),
        ('perm_academy_member_owner_remove', 'academy.member.owner.remove', 'Remove academy owners', 'Allows removing academy owner membership.'),
        ('perm_academy_member_admin_assign', 'academy.member.admin.assign', 'Assign academy admins', 'Allows assigning academy admin membership.'),
        ('perm_academy_member_admin_remove', 'academy.member.admin.remove', 'Remove academy admins', 'Allows removing academy admin membership.'),
        ('perm_academy_member_coach_assign', 'academy.member.coach.assign', 'Assign academy coaches', 'Allows assigning academy coach membership.'),
        ('perm_academy_member_coach_remove', 'academy.member.coach.remove', 'Remove academy coaches', 'Allows removing academy coach membership.'),
        ('perm_academy_claim_submit', 'academy.claim.submit', 'Submit academy claims', 'Allows submitting academy ownership claims.'),
        ('perm_academy_claim_read', 'academy.claim.read', 'Read academy claims', 'Allows reading academy ownership claim records.'),
        ('perm_academy_claim_search', 'academy.claim.search', 'Search academy claims', 'Allows listing and searching academy ownership claims.'),
        ('perm_academy_claim_update', 'academy.claim.update', 'Update academy claims', 'Allows updating academy ownership claim metadata.'),
        ('perm_academy_claim_reject', 'academy.claim.reject', 'Reject academy claims', 'Allows rejecting academy ownership claims.'),
        ('perm_academy_claim_cancel', 'academy.claim.cancel', 'Cancel academy claims', 'Allows cancelling academy ownership claims.'),
        ('perm_academy_claim_audit_read', 'academy.claim.audit.read', 'Read academy claim audit', 'Allows reading academy claim audit records.'),
        ('perm_academy_verification_submit', 'academy.verification.submit', 'Submit academy verification', 'Allows submitting academy verification material.'),
        ('perm_academy_verification_read', 'academy.verification.read', 'Read academy verification', 'Allows reading academy verification records.'),
        ('perm_academy_verification_update', 'academy.verification.update', 'Update academy verification', 'Allows updating academy verification records.'),
        ('perm_academy_verification_review', 'academy.verification.review', 'Review academy verification', 'Allows reviewing academy verification material.'),
        ('perm_academy_verification_approve', 'academy.verification.approve', 'Approve academy verification', 'Allows approving academy verification.'),
        ('perm_academy_verification_reject', 'academy.verification.reject', 'Reject academy verification', 'Allows rejecting academy verification.'),
        ('perm_academy_verification_audit_read', 'academy.verification.audit.read', 'Read academy verification audit', 'Allows reading academy verification audit records.'),
        ('perm_academy_invitation_create', 'academy.invitation.create', 'Create academy invitations', 'Allows creating academy invitations.'),
        ('perm_academy_invitation_read', 'academy.invitation.read', 'Read academy invitations', 'Allows reading academy invitations.'),
        ('perm_academy_invitation_cancel', 'academy.invitation.cancel', 'Cancel academy invitations', 'Allows cancelling academy invitations.'),
        ('perm_academy_invitation_resend', 'academy.invitation.resend', 'Resend academy invitations', 'Allows resending academy invitations.'),
        ('perm_academy_invitation_accept', 'academy.invitation.accept', 'Accept academy invitations', 'Allows accepting academy invitations.'),
        ('perm_academy_invitation_expire', 'academy.invitation.expire', 'Expire academy invitations', 'Allows expiring academy invitations.'),
        ('perm_academy_claim_reminder_create', 'academy.claim_reminder.create', 'Create academy claim reminders', 'Allows sending or queueing academy claim reminders.'),
        ('perm_academy_claim_reminder_read', 'academy.claim_reminder.read', 'Read academy claim reminders', 'Allows reading academy claim reminder records.'),
        ('perm_academy_claim_reminder_audit_read', 'academy.claim_reminder.audit.read', 'Read academy claim reminder audit', 'Allows reading academy claim reminder audit records.'),
        ('perm_academy_analytics_read', 'academy.analytics.read', 'Read academy analytics', 'Allows reading academy analytics.'),
        ('perm_academy_audit_read', 'academy.audit.read', 'Read academy audit logs', 'Allows reading academy domain audit logs.'),
        ('perm_academy_payment_status_read', 'academy.payment_status.read', 'Read academy payment status', 'Allows reading academy payment capability summaries.'),
        ('perm_academy_payment_onboarding_start', 'academy.payment_onboarding.start', 'Start academy payment onboarding', 'Allows starting academy payment onboarding.'),
        ('perm_academy_payment_onboarding_refresh', 'academy.payment_onboarding.refresh', 'Refresh academy payment onboarding', 'Allows refreshing academy payment onboarding status or links.'),
        ('perm_academy_payment_onboarding_disconnect', 'academy.payment_onboarding.disconnect', 'Disconnect academy payment onboarding', 'Allows requesting academy payment account disconnect flows.'),
        ('perm_payment_client_read', 'payment.client.read', 'Read payment clients', 'Allows reading payment client records.'),
        ('perm_payment_client_update', 'payment.client.update', 'Update payment clients', 'Allows updating payment client records.'),
        ('perm_payment_allocation_read', 'payment.allocation.read', 'Read payment allocations', 'Allows reading payment allocation records.'),
        ('perm_payment_allocation_search', 'payment.allocation.search', 'Search payment allocations', 'Allows listing and searching payment allocation records.'),
        ('perm_payment_payee_create', 'payment.payee.create', 'Create payees', 'Allows creating payment payee records.'),
        ('perm_payment_payee_read', 'payment.payee.read', 'Read payees', 'Allows reading payment payee records.'),
        ('perm_payment_payee_search', 'payment.payee.search', 'Search payees', 'Allows listing and searching payment payee records.'),
        ('perm_payment_payee_update', 'payment.payee.update', 'Update payees', 'Allows updating payment payee records.'),
        ('perm_payment_payee_archive', 'payment.payee.archive', 'Archive payees', 'Allows archiving payment payee records.'),
        ('perm_payment_payee_account_create', 'payment.payee_account.create', 'Create payee accounts', 'Allows creating payment payee account records.'),
        ('perm_payment_payee_account_read', 'payment.payee_account.read', 'Read payee accounts', 'Allows reading payment payee account records.'),
        ('perm_payment_payee_account_update', 'payment.payee_account.update', 'Update payee accounts', 'Allows updating payment payee account records.'),
        ('perm_payment_payee_account_disconnect', 'payment.payee_account.disconnect', 'Disconnect payee accounts', 'Allows disconnecting payment payee accounts.'),
        ('perm_payment_payee_account_onboarding_start', 'payment.payee_account.onboarding.start', 'Start payee account onboarding', 'Allows starting payee account onboarding.'),
        ('perm_payment_payee_account_refresh', 'payment.payee_account.refresh', 'Refresh payee accounts', 'Allows refreshing payment payee account status or links.'),
        ('perm_payment_commission_policy_create', 'payment.commission_policy.create', 'Create commission policies', 'Allows creating payment commission policies.'),
        ('perm_payment_commission_policy_read', 'payment.commission_policy.read', 'Read commission policies', 'Allows reading payment commission policies.'),
        ('perm_payment_commission_policy_search', 'payment.commission_policy.search', 'Search commission policies', 'Allows listing and searching payment commission policies.'),
        ('perm_payment_commission_policy_update', 'payment.commission_policy.update', 'Update commission policies', 'Allows updating payment commission policies.'),
        ('perm_payment_commission_policy_archive', 'payment.commission_policy.archive', 'Archive commission policies', 'Allows archiving payment commission policies.'),
        ('perm_payment_refund_create', 'payment.refund.create', 'Create payment refunds', 'Allows creating payment refund records.'),
        ('perm_payment_refund_search', 'payment.refund.search', 'Search payment refunds', 'Allows listing and searching payment refund records.'),
        ('perm_payment_refund_reconcile', 'payment.refund.reconcile', 'Reconcile payment refunds', 'Allows reconciling payment refund records.'),
        ('perm_payment_settlement_search', 'payment.settlement.search', 'Search settlements', 'Allows listing and searching payment settlements.'),
        ('perm_payment_settlement_read', 'payment.settlement.read', 'Read settlements', 'Allows reading payment settlement records.'),
        ('perm_payment_settlement_hold', 'payment.settlement.hold', 'Hold settlements', 'Allows placing payment settlements on hold.'),
        ('perm_payment_settlement_release', 'payment.settlement.release', 'Release settlements', 'Allows releasing payment settlements from hold.'),
        ('perm_payment_report_settlement_read', 'payment.report.settlement.read', 'Read settlement reports', 'Allows reading payment settlement reports.'),
        ('perm_payment_webhook_ingest', 'payment.webhook.ingest', 'Ingest payment webhooks', 'Allows ingesting payment provider webhooks.'),
        ('perm_payment_reconciliation_run', 'payment.reconciliation.run', 'Run payment reconciliation', 'Allows running payment reconciliation jobs.'),
        ('perm_payment_reconciliation_read', 'payment.reconciliation.read', 'Read payment reconciliation', 'Allows reading payment reconciliation results.'),
        ('perm_payment_audit_read', 'payment.audit.read', 'Read payment audit', 'Allows reading payment audit records.'),
        ('perm_payment_payout_request_create', 'payment.payout_request.create', 'Create payment payout requests', 'Allows creating payout requests through payment APIs.'),
        ('perm_payment_payout_request_read', 'payment.payout_request.read', 'Read payment payout requests', 'Allows reading payout requests through payment APIs.'),
        ('perm_payment_payout_request_search', 'payment.payout_request.search', 'Search payment payout requests', 'Allows listing and searching payout requests through payment APIs.'),
        ('perm_payment_payout_request_approve', 'payment.payout_request.approve', 'Approve payment payout requests', 'Allows approving payout requests through payment APIs.'),
        ('perm_payment_payout_request_reject', 'payment.payout_request.reject', 'Reject payment payout requests', 'Allows rejecting payout requests through payment APIs.'),
        ('perm_payment_payout_request_hold', 'payment.payout_request.hold', 'Hold payment payout requests', 'Allows placing payout requests on hold through payment APIs.'),
        ('perm_payment_payout_request_release', 'payment.payout_request.release', 'Release payment payout requests', 'Allows releasing payout requests through payment APIs.'),
        ('perm_payment_payout_request_mark_paid', 'payment.payout_request.mark_paid', 'Mark payment payout requests paid', 'Allows marking payout requests as paid through payment APIs.'),
        ('perm_payment_payout_request_cancel', 'payment.payout_request.cancel', 'Cancel payment payout requests', 'Allows cancelling payout requests through payment APIs.'),
        ('perm_user_search', 'user.search', 'Search users', 'Allows listing and searching managed users.'),
        ('perm_user_status_disable', 'user.status.disable', 'Disable users', 'Allows disabling managed users.'),
        ('perm_user_status_enable', 'user.status.enable', 'Enable users', 'Allows enabling managed users.'),
        ('perm_user_protected_manage', 'user.protected.manage', 'Manage protected users', 'Allows managing protected user records.'),
        ('perm_user_audit_read', 'user.audit.read', 'Read user audit', 'Allows reading user audit records.'),
        ('perm_user_password_change_self', 'user.password.change.self', 'Change own user password', 'Allows changing the authenticated user password.'),
        ('perm_user_password_reset_request', 'user.password.reset.request', 'Request user password reset', 'Allows requesting a user password reset.'),
        ('perm_user_password_reset_confirm', 'user.password.reset.confirm', 'Confirm user password reset', 'Allows confirming a user password reset.'),
        ('perm_user_password_reset_send_managed', 'user.password.reset.send_managed', 'Send managed user password reset', 'Allows sending managed user password reset flows.'),
        ('perm_user_session_read', 'user.session.read', 'Read user sessions', 'Allows reading user session records.'),
        ('perm_user_session_revoke', 'user.session.revoke', 'Revoke user sessions', 'Allows revoking user sessions.'),
        ('perm_user_mfa_read', 'user.mfa.read', 'Read user MFA', 'Allows reading user MFA state.'),
        ('perm_user_mfa_setup', 'user.mfa.setup', 'Set up user MFA', 'Allows setting up user MFA.'),
        ('perm_user_mfa_verify', 'user.mfa.verify', 'Verify user MFA', 'Allows verifying user MFA.'),
        ('perm_user_mfa_disable', 'user.mfa.disable', 'Disable user MFA', 'Allows disabling user MFA.'),
        ('perm_organisation_search', 'organisation.search', 'Search organisations', 'Allows listing and searching organisation records.'),
        ('perm_organisation_delete', 'organisation.delete', 'Delete organisations', 'Allows deleting organisation records.'),
        ('perm_organisation_activate', 'organisation.activate', 'Activate organisations', 'Allows activating organisation records.'),
        ('perm_organisation_suspend', 'organisation.suspend', 'Suspend organisations', 'Allows suspending organisation records.'),
        ('perm_organisation_archive', 'organisation.archive', 'Archive organisations', 'Allows archiving organisation records.'),
        ('perm_organisation_profile_read', 'organisation.profile.read', 'Read organisation profile', 'Allows reading organisation profile records.'),
        ('perm_organisation_profile_update', 'organisation.profile.update', 'Update organisation profile', 'Allows updating organisation profile records.'),
        ('perm_organisation_settings_read', 'organisation.settings.read', 'Read organisation settings', 'Allows reading organisation settings.'),
        ('perm_organisation_settings_update', 'organisation.settings.update', 'Update organisation settings', 'Allows updating organisation settings.'),
        ('perm_organisation_application_create', 'organisation.application.create', 'Create organisation applications', 'Allows creating applications under an organisation.'),
        ('perm_organisation_application_read', 'organisation.application.read', 'Read organisation applications', 'Allows reading organisation application records.'),
        ('perm_organisation_application_search', 'organisation.application.search', 'Search organisation applications', 'Allows listing organisation application records.'),
        ('perm_organisation_application_update', 'organisation.application.update', 'Update organisation applications', 'Allows updating organisation application records.'),
        ('perm_organisation_application_archive', 'organisation.application.archive', 'Archive organisation applications', 'Allows archiving organisation application records.'),
        ('perm_organisation_service_read', 'organisation.service.read', 'Read organisation services', 'Allows reading enabled organisation application services.'),
        ('perm_organisation_service_enable', 'organisation.service.enable', 'Enable organisation services', 'Allows enabling organisation application services.'),
        ('perm_organisation_service_disable', 'organisation.service.disable', 'Disable organisation services', 'Allows disabling organisation application services.'),
        ('perm_organisation_resource_link_read', 'organisation.resource_link.read', 'Read organisation resource links', 'Allows reading organisation resource link records.'),
        ('perm_organisation_resource_link_create', 'organisation.resource_link.create', 'Create organisation resource links', 'Allows creating organisation resource link records.'),
        ('perm_organisation_resource_link_update', 'organisation.resource_link.update', 'Update organisation resource links', 'Allows updating organisation resource link records.'),
        ('perm_organisation_resource_link_delete', 'organisation.resource_link.delete', 'Delete organisation resource links', 'Allows deleting organisation resource link records.'),
        ('perm_organisation_audit_read', 'organisation.audit.read', 'Read organisation audit', 'Allows reading organisation audit records.'),
        ('perm_authorisation_permission_delete', 'authorisation.permission.delete', 'Delete permissions', 'Allows deleting or deactivating permission definitions.'),
        ('perm_authorisation_role_delete', 'authorisation.role.delete', 'Delete roles', 'Allows deleting or deactivating role bundles.'),
        ('perm_authorisation_delegation_manage', 'authorisation.delegation.manage', 'Manage authorisation delegation', 'Allows managing delegated administration limits.'),
        ('perm_authorisation_catalog_seed', 'authorisation.catalog.seed', 'Seed authorisation catalog', 'Allows seeding or reconciling service permission catalogs.'),
        ('perm_authorisation_audit_read', 'authorisation.audit.read', 'Read authorisation audit', 'Allows reading authorisation audit events.'),
        ('perm_authorisation_manage', 'authorisation.manage', 'Manage authorisation', 'Allows managing roles, permissions, and assignments.')
    ON CONFLICT (id) DO UPDATE
    SET code = EXCLUDED.code,
        name = EXCLUDED.name,
        description = EXCLUDED.description,
        updated_at = now();

    INSERT INTO roles (id, key, name, description, level, assignable, system_role)
    VALUES
        ('role_user', 'USER', 'User', 'Legacy-compatible application user role.', 100, true, true),
        ('role_standard_user', 'STANDARD_USER', 'Standard User', 'Default authenticated user.', 100, true, true),
        ('role_member', 'MEMBER', 'Member', 'Member access role.', 200, true, true),
        ('role_coach', 'COACH', 'Coach', 'Coach access role.', 300, true, true),
        ('role_academy_admin', 'ACADEMY_ADMIN', 'Academy Admin', 'Legacy-compatible academy administrator role.', 400, true, true),
        ('role_academy_owner', 'ACADEMY_OWNER', 'Academy Owner', 'Legacy-compatible academy owner role.', 500, true, true),
        ('role_application_admin', 'APPLICATION_ADMIN', 'Application Admin', 'Application administration role.', 600, true, true),
        ('role_organisation_admin', 'ORGANISATION_ADMIN', 'Organisation Admin', 'Organisation administration role.', 700, true, true),
        ('role_organisation_owner', 'ORGANISATION_OWNER', 'Organisation Owner', 'Organisation owner role.', 800, true, true),
        ('role_platform_admin', 'PLATFORM_ADMIN', 'Platform Admin', 'Legacy-compatible platform administrator role.', 900, true, true),
        ('role_super_admin', 'SUPER_ADMIN', 'Super Administrator', 'Legacy-compatible platform owner role.', 1000, false, true),
        ('role_admin', 'ADMIN', 'Administrator', 'Legacy-compatible administrator role.', 1000, false, true)
    ON CONFLICT (key) DO UPDATE
    SET name = EXCLUDED.name,
        description = EXCLUDED.description,
        level = EXCLUDED.level,
        assignable = EXCLUDED.assignable,
        system_role = EXCLUDED.system_role,
        updated_at = now();

    INSERT INTO role_permissions (role_id, permission_id)
    SELECT r.id, p.id
    FROM roles r
    CROSS JOIN permissions p
    WHERE r.key IN ('SUPER_ADMIN', 'ADMIN')
    ON CONFLICT DO NOTHING;

    INSERT INTO role_permissions (role_id, permission_id)
    SELECT r.id, p.id
    FROM roles r
    JOIN permissions p ON p.code IN (
        'academy.view', 'academy.read', 'academy.search',
        'course.read', 'course.search', 'course.activity.read', 'course.type.read',
        'booking.create', 'booking.read', 'booking.view',
        'auth.logout', 'auth.refresh', 'auth.password.change', 'auth.session.read', 'auth.session.revoke', 'auth.mfa.setup', 'auth.mfa.verify',
        'account.read'
    )
    WHERE r.key IN ('USER', 'STANDARD_USER')
    ON CONFLICT DO NOTHING;

    INSERT INTO role_permissions (role_id, permission_id)
    SELECT r.id, p.id
    FROM roles r
    JOIN permissions p ON p.code IN (
        'academy.create', 'academy.view', 'academy.read', 'academy.edit', 'academy.update', 'academy.delete',
        'academy.claim.view', 'academy.claim.approve', 'academy.verify', 'academy.unverify',
        'academy.suspend', 'academy.activate', 'academy.archive', 'academy.restore',
        'academy.audit.view', 'academy.public.enabled', 'academy.search',
        'academy.member.read', 'academy.member.add', 'academy.member.assign', 'academy.member.remove', 'academy.membership.read',
        'academy.profile.read', 'academy.profile.update', 'academy.social.read', 'academy.social.update',
        'course.create', 'course.read', 'course.search', 'course.update', 'course.delete',
        'course.activity.create', 'course.activity.read', 'course.activity.update', 'course.activity.delete',
        'course.type.create', 'course.type.read', 'course.type.update', 'course.type.delete',
        'booking.create', 'booking.read', 'booking.view', 'booking.cancel', 'booking.confirm', 'booking.complete',
        'booking.payment_received', 'booking.payment_link',
        'booking.participant.create', 'booking.participant.read', 'booking.participant.attendance.record',
        'payment.client.create', 'payment.checkout.create', 'payment.checkout.callback',
        'payment.course_occurrence_checkout.create', 'payment.course_occurrence_checkout.callback',
        'payment.create', 'payment.read', 'payment.capture', 'payment.cancel',
        'payment.search', 'payment.report.revenue.read', 'payment.report.refund.read', 'payment.report.platform_revenue.read',
        'payment.refund', 'payment.refund.read', 'payment.payee.balance.read', 'payment.webhook.receive', 'payment.outbox.dispatch',
        'payout.request.create', 'payout.request.read', 'payout.request.approve', 'payout.request.reject',
        'payout.request.hold', 'payout.request.release', 'payout.request.mark_paid', 'payout.request.cancel',
        'auth.register', 'auth.logout', 'auth.refresh', 'auth.password.change', 'auth.session.read', 'auth.session.revoke',
        'auth.mfa.setup', 'auth.mfa.verify', 'auth.credentials.authenticate',
        'account.read', 'user.create', 'user.read', 'user.update', 'user.delete', 'user.mutate',
        'organisation.create', 'organisation.read', 'organisation.update', 'organisation.application.manage',
        'authorisation.permission.create', 'authorisation.permission.read', 'authorisation.permission.search', 'authorisation.permission.update',
        'authorisation.role.create', 'authorisation.role.read', 'authorisation.role.search', 'authorisation.role.update',
        'authorisation.role_permission.add', 'authorisation.role_permission.assign', 'authorisation.role_permission.read', 'authorisation.role_permission.remove',
        'authorisation.user_role.assign', 'authorisation.user_role.read', 'authorisation.user_role.remove',
        'authorisation.user_permission.assign', 'authorisation.user_permission.read', 'authorisation.user_permission.remove',
        'authorisation.effective_permission.read', 'authorisation.authorize', 'authorisation.manage'
    )
    WHERE r.key = 'PLATFORM_ADMIN'
    ON CONFLICT DO NOTHING;

    INSERT INTO role_permissions (role_id, permission_id)
    SELECT r.id, p.id
    FROM roles r
    JOIN permissions p ON p.code IN (
        'academy.view', 'academy.read', 'academy.search', 'academy.edit', 'academy.update', 'academy.audit.view',
        'academy.member.read', 'academy.member.add', 'academy.member.assign', 'academy.member.remove', 'academy.membership.read',
        'academy.profile.read', 'academy.profile.update', 'academy.social.read', 'academy.social.update',
        'course.create', 'course.read', 'course.search', 'course.update', 'course.delete',
        'course.activity.create', 'course.activity.read', 'course.activity.update', 'course.activity.delete',
        'course.type.read',
        'booking.create', 'booking.read', 'booking.view', 'booking.cancel', 'booking.confirm', 'booking.complete',
        'booking.payment_received', 'booking.payment_link',
        'booking.participant.create', 'booking.participant.read', 'booking.participant.attendance.record',
        'payment.read', 'payment.search', 'payment.report.revenue.read', 'payment.report.refund.read',
        'payment.refund.read', 'payment.payee.balance.read',
        'payout.request.create', 'payout.request.read', 'payout.request.cancel'
    )
    WHERE r.key IN ('ACADEMY_OWNER', 'ACADEMY_ADMIN')
    ON CONFLICT DO NOTHING;
END;
$$;
